export const Zones = [
  // Zone A - Regional Capitals
  { name: 'Ngaoundéré', type: 'A' },
  { name: 'Yaoundé', type: 'A' },
  { name: 'Bertoua', type: 'A' },
  { name: 'Maroua', type: 'A' },
  { name: 'Douala', type: 'A' },
  { name: 'Garoua', type: 'A' },
  { name: 'Bamenda', type: 'A' },
  { name: 'Ebolowa', type: 'A' },
  { name: 'Buea', type: 'A' },
  { name: 'Bafoussam', type: 'A' },

  // Zone B - Divisional Headquarters
  { name: 'Mbalmayo', type: 'B' },
  { name: 'Monatélé', type: 'B' },
  { name: 'Bafia', type: 'B' },
  { name: 'Nanga Eboko', type: 'B' },
  { name: 'Edea', type: 'B' },
  { name: 'Nkongsamba', type: 'B' },
  { name: 'Kumba', type: 'B' },
  { name: 'Limbe', type: 'B' },
  { name: 'Mamfe', type: 'B' },
  { name: 'Kumbo', type: 'B' },
  { name: 'Wum', type: 'B' },
  { name: 'Ndop', type: 'B' },
  { name: 'Dschang', type: 'B' },
  { name: 'Foumban', type: 'B' },
  { name: 'Bangangté', type: 'B' },
  { name: 'Bafang', type: 'B' },
  { name: 'Sangmélima', type: 'B' },
  { name: 'Kribi', type: 'B' },
  { name: 'Guider', type: 'B' },
  { name: 'Poli', type: 'B' },
  { name: 'Batouri', type: 'B' },
  { name: 'Abong-Mbang', type: 'B' },
  { name: 'Meiganga', type: 'B' },
  { name: 'Tibati', type: 'B' },
  { name: 'Mokolo', type: 'B' },
  { name: 'Kousseri', type: 'B' },
  { name: 'Yagoua', type: 'B' },

  // Zone C - Subdivisional HQs and Villages
  { name: 'Obala', type: 'C' },
  { name: 'Soa', type: 'C' },
  { name: 'Esse', type: 'C' },
  { name: 'Bikok', type: 'C' },
  { name: 'Dibombari', type: 'C' },
  { name: 'Loum', type: 'C' },
  { name: 'Manjo', type: 'C' },
  { name: 'Ekondo-Titi', type: 'C' },
  { name: 'Muyuka', type: 'C' },
  { name: 'Tiko', type: 'C' },
  { name: 'Banga', type: 'C' },
  { name: 'Bali', type: 'C' },
  { name: 'Fundong', type: 'C' },
  { name: 'Ndu', type: 'C' },
  { name: 'Ako', type: 'C' },
  { name: 'Mbengwi', type: 'C' },
  { name: 'Banyo', type: 'C' },
  { name: 'Baham', type: 'C' },
  { name: 'Bandjoun', type: 'C' },
  { name: 'Lomié', type: 'C' },
  { name: 'Mindourou', type: 'C' },
  { name: 'Ngaoundal', type: 'C' },
  { name: 'Nyambaka', type: 'C' },
  { name: 'Mora', type: 'C' },
  { name: 'Kaélé', type: 'C' },
  { name: 'Pouss', type: 'C' },
  { name: 'Akom II', type: 'C' },
  { name: 'Djoum', type: 'C' },
  { name: 'Oveng', type: 'C' },
  { name: 'Tcholliré', type: 'C' },
  { name: 'Rey Bouba', type: 'C' }
]
